**Math Word Problem Readability Score**

Experimented with all variables Raw attributes
 - (MathSymbolsPerSentence), (MathSymbolsPerSentence), etc...

Raw attributes - GF*, FK*, SMOG*, ARI*, CL*

**MOUNTING THE DRIVE**

In [132]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [133]:
import warnings 
warnings.filterwarnings("ignore")

**IMPORT THE LIBRARIES**

In [134]:
from numpy import nan 
import tensorflow as tf 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from keras.models import Sequential
from tensorflow.keras.layers import Dense

In [135]:
import pandas as pd
import numpy as np
import scipy as scp
import sklearn

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn import metrics 
from sklearn.metrics import confusion_matrix

import statsmodels.api as sm 
import matplotlib.pyplot as plt

In [136]:
import os
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV, cross_val_score, StratifiedKFold
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, classification_report
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder

In [137]:
import gensim
import nltk
nltk.download('stopwords')
nltk.download('punkt')
import re
from bs4 import BeautifulSoup
import csv
from nltk.tokenize import sent_tokenize
import nltk
!pip install nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize
stop_words = set(stopwords.words('english'))
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (3.8.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk) (8.1.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk) (2022.10.31)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk) (4.65.0)

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!

True

**READ THE DATA**

In [138]:
df = pd.read_csv("/content/drive/MyDrive/newpro/MWP_indices_lastexperiment/data.csv")

**CHECK THE FIRST FEW ROWS OF THE DATA**

In [139]:
df.head()

,Problem,Level,Type,Solution,Extracted words(List),Extracted Num(List)
0,There are constants alpha and beta suc...,Level 5,Algebra,The numerator x^2 - 80x + 1551 factors as (...,"['There', 'are', 'constants', 'alpha', 'and', ...","['2', '80', '1551', '2', '57', '2970']"
1,The length of the segment between the points ...,Level 5,Algebra,"By the distance formula, the distance from (2...","['The', 'length', 'of', 'the', 'segment', 'bet...","['2', '4', '4', '1', '2', '10']"
2,Chewbacca has 20 pieces of cherry gum and 30 p...,Level 5,Algebra,"If Chewbacca loses one pack of cherry gum, the...","['Chewbacca', 'has', 'pieces', 'of', 'cherry',...","['20', '30', '5']"
3,"For some constants a and b, let [f(x) = ...",Level 5,Algebra,"Setting x = 3, we get f(3) = -1. Since -1...","['For', 'some', 'constants', 'a', 'and', 'b', ...","['2', '8', '3', '2']"
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,Level 2,Algebra,"The arithmetic sequence 1, 3, 5, dots , 17,...","['Calculate', 'the', 'sum', 'cdots']","['1', '3', '5', '15', '17']"

**EXTRACT TWO COLUMNS OF THE DATA**

In [140]:
df = df.iloc[:,0:2]
df

                                               Problem    Level
0     There are constants    alpha  and    beta  suc...  Level 5
1     The length of the segment between the points  ...  Level 5
2     Chewbacca has 20 pieces of cherry gum and 30 p...  Level 5
3     For some constants  a  and  b,  let   [f(x) = ...  Level 5
4     Calculate the sum  1 + 3 + 5 +   cdots + 15 + ...  Level 2
...                                                 ...      ...
1739  What is the slope of the line passing through ...  Level 2
1740  Evaluate  i^{11} + i^{16} + i^{21} + i^{26} + ...  Level 4
1741  If  a  is a constant such that  4x^2 - 12x + a...  Level 3
1742  Given  a   star b = a^2 + 2ab + b^2 , what is ...  Level 3
1743  The graph of the function  f(x)  is shown belo...  Level 5

[1744 rows x 2 columns]

**CHECK FIRST FEW ROWS OF THE DATA**

In [141]:
df.head()

                                            Problem    Level
0  There are constants    alpha  and    beta  suc...  Level 5
1  The length of the segment between the points  ...  Level 5
2  Chewbacca has 20 pieces of cherry gum and 30 p...  Level 5
3  For some constants  a  and  b,  let   [f(x) = ...  Level 5
4  Calculate the sum  1 + 3 + 5 +   cdots + 15 + ...  Level 2

**CHECK THE SHAPE OF THE DATA**

In [142]:
df.shape

(1744, 2)

**CHECK FOR THE NUMBER OF UNIQUE CLASSES IN EACH COLUMN**

In [143]:
df.nunique()

Problem     1744
Level          5
dtype: int64

**REMOVAL OF THE STRING PART (Level) FROM THE COLUMN "Level"**

In [144]:
df.iloc[:,1].replace(['Level 1', 'Level 2', 'Level 3', 'Level 4', 'Level 5'],
                        [1, 2, 3, 4, 5], inplace=True)

In [145]:
df.head()

                                            Problem   Level
0  There are constants    alpha  and    beta  suc...       5
1  The length of the segment between the points  ...       5
2  Chewbacca has 20 pieces of cherry gum and 30 p...       5
3  For some constants  a  and  b,  let   [f(x) = ...       5
4  Calculate the sum  1 + 3 + 5 +   cdots + 15 + ...       2

In [146]:
df.nunique()

Problem     1744
Level          5
dtype: int64

**READ THE DATA OF MATH VOCAB**

In [147]:
mathvocab = pd.read_csv("/content/drive/MyDrive/newpro/MWP_indices_lastexperiment/mathwords.csv")

In [148]:
mathvocab.head()

   Unnamed: 0  Word  Value
0           0     x   2675
1           1  What    597
2           2  frac    573
3           3     f    544
4           4     b    518

In [149]:
mwl = mathvocab.iloc[:,0:2]
mwl.head()

   Unnamed: 0  Word
0           0     x
1           1  What
2           2  frac
3           3     f
4           4     b

In [150]:
mwl.drop(mwl.columns[[0]], axis=1, inplace=True)
mwl.head()

   Word
0     x
1  What
2  frac
3     f
4     b

**CREATED LIST OF ALL MATH VOCAB WORDS**

In [151]:
list = mwl['Word'].tolist()

print("the list of a single column from the dataframe\n",
        list,
        "\n",
        type(list))

the list of a single column from the dataframe

**EXTRACTING MATH VOCAB WORDS FROM THE COLUMN 'Problem'**

In [153]:
query = '|'.join(list)
df['word'] = df['Problem '].str.findall(r'\b({})\b'.format(query)) 

print(df)

                                               Problem   Level   \
0     There are constants    alpha  and    beta  suc...       5
1     The length of the segment between the points  ...       5
2     Chewbacca has 20 pieces of cherry gum and 30 p...       5
3     For some constants  a  and  b,  let   [f(x) = ...       5
4     Calculate the sum  1 + 3 + 5 +   cdots + 15 + ...       2
...                                                 ...     ...
1739  What is the slope of the line passing through ...       2
1740  Evaluate  i^{11} + i^{16} + i^{21} + i^{26} + ...       4
1741  If  a  is a constant such that  4x^2 - 12x + a...       3
1742  Given  a   star b = a^2 + 2ab + b^2 , what is ...       3
1743  The graph of the function  f(x)  is shown belo...       5

                                                   word
0     [There, constants, alpha, beta, frac, x, alpha...
1     [The, length, segment, points, sqrt, units, Wh...
2     [Chewbacca, pieces, cherry, gum, pieces, grape...
3     [For, constants, b, let, f, x, left, begin, ar...
4                               [Calculate, sum, cdots]
...                                                 ...
1739                       [What, slope, line, passing]
1740                                         [Evaluate]
1741                   [If, constant, square, binomial]
1742             [Given, star, b, b, value, star, b, b]
1743  [The, graph, function, f, x, shown, How, many,...

[1744 rows x 3 columns]

In [154]:
df.head()

,Problem,Level,word
0,There are constants alpha and beta suc...,5,"[There, constants, alpha, beta, frac, x, alpha..."
1,The length of the segment between the points ...,5,"[The, length, segment, points, sqrt, units, Wh..."
2,Chewbacca has 20 pieces of cherry gum and 30 p...,5,"[Chewbacca, pieces, cherry, gum, pieces, grape..."
3,"For some constants a and b, let [f(x) = ...",5,"[For, constants, b, let, f, x, left, begin, ar..."
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,2,"[Calculate, sum, cdots]"

In [155]:
df['liststring'] = df.word.apply(lambda x: ', '.join([str(i) for i in x]))

In [156]:
df.head()

,Problem,Level,word,liststring
0,There are constants alpha and beta suc...,5,"[There, constants, alpha, beta, frac, x, alpha...","There, constants, alpha, beta, frac, x, alpha,..."
1,The length of the segment between the points ...,5,"[The, length, segment, points, sqrt, units, Wh...","The, length, segment, points, sqrt, units, Wha..."
2,Chewbacca has 20 pieces of cherry gum and 30 p...,5,"[Chewbacca, pieces, cherry, gum, pieces, grape...","Chewbacca, pieces, cherry, gum, pieces, grape,..."
3,"For some constants a and b, let [f(x) = ...",5,"[For, constants, b, let, f, x, left, begin, ar...","For, constants, b, let, f, x, left, begin, arr..."
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,2,"[Calculate, sum, cdots]","Calculate, sum, cdots"

**DROPPED THE COLUMN "word" FROM THE DATAFRAME**

In [157]:
df_liststring = df.drop(['word'], axis = 1)

In [158]:
df_liststring.head()

,Problem,Level,liststring
0,There are constants alpha and beta suc...,5,"There, constants, alpha, beta, frac, x, alpha,..."
1,The length of the segment between the points ...,5,"The, length, segment, points, sqrt, units, Wha..."
2,Chewbacca has 20 pieces of cherry gum and 30 p...,5,"Chewbacca, pieces, cherry, gum, pieces, grape,..."
3,"For some constants a and b, let [f(x) = ...",5,"For, constants, b, let, f, x, left, begin, arr..."
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,2,"Calculate, sum, cdots"

**COLUMN "liststring" CONTAINS ALL THE MATH VOCAB WORDS THAT ARE PRESENT IN THE COLUMN "Problem".**

In [159]:
df_liststring['liststring']=df_liststring['liststring'].str.replace(',','')

In [160]:
df_liststring.head(10)

,Problem,Level,liststring
0,There are constants alpha and beta suc...,5,There constants alpha beta frac x alpha x beta...
1,The length of the segment between the points ...,5,The length segment points sqrt units What prod...
2,Chewbacca has 20 pieces of cherry gum and 30 p...,5,Chewbacca pieces cherry gum pieces grape gum S...
3,"For some constants a and b, let [f(x) = ...",5,For constants b let f x left begin array cl ax...
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,2,Calculate sum cdots
5,What is the number of units in the area of the...,4,What number units area circle center P passing...
6,Find the positive value of n such that the e...,4,Find positive value n equation nx exactly one ...
7,Find the leading coefficient in the polynomial...,3,Find leading coefficient polynomial x x x x si...
8,Find the greatest a such that frac{7 sqr...,5,Find greatest frac sqrt sqrt
9,The Bank of Springfield's Super High Yield sav...,4,The Bank Springfield Super High Yield savings ...

**FUNCTION TO COUNT NUMBER OF MATH WORD COUNT IN THE COLUMN "Liststring".**

**mathword_count = TMVW**

In [161]:
def word_length(df_col):
  number_of_words = len(df_col.split())
  # print(df_col.split())
  return number_of_words

In [162]:
df_liststring['mathword_count'] = df_liststring['liststring'].apply(word_length)

In [163]:
df_liststring.head()

,Problem,Level,liststring,mathword_count
0,There are constants alpha and beta suc...,5,There constants alpha beta frac x alpha x beta...,15
1,The length of the segment between the points ...,5,The length segment points sqrt units What prod...,10
2,Chewbacca has 20 pieces of cherry gum and 30 p...,5,Chewbacca pieces cherry gum pieces grape gum S...,44
3,"For some constants a and b, let [f(x) = ...",5,For constants b let f x left begin array cl ax...,31
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,2,Calculate sum cdots,3

**FUNCTION TO COUNT THE TOTAL NUMBER OF SENTENCES IN EACH MATH WORD PROBLEM**

In [164]:
def count_sentences(data):
  number_of_sentences = sent_tokenize(data)
  return len(number_of_sentences)

In [165]:
df_liststring['countsent'] = df_liststring['Problem '].apply(count_sentences)

In [166]:
df_liststring.head()

,Problem,Level,liststring,mathword_count,countsent
0,There are constants alpha and beta suc...,5,There constants alpha beta frac x alpha x beta...,15,2
1,The length of the segment between the points ...,5,The length segment points sqrt units What prod...,10,2
2,Chewbacca has 20 pieces of cherry gum and 30 p...,5,Chewbacca pieces cherry gum pieces grape gum S...,44,5
3,"For some constants a and b, let [f(x) = ...",5,For constants b let f x left begin array cl ax...,31,3
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,2,Calculate sum cdots,3,1

**FUNCTION TO COUNT ALL NUMBER OF WORDS IN EACH MATH PROBLEM**

In [167]:
def count_allwords(data):
  number_of_words = len(data.split())
  return number_of_words

In [168]:
df_liststring['allwords'] = df_liststring['Problem '].apply(count_allwords)

In [169]:
df_liststring.head()

,Problem,Level,liststring,mathword_count,countsent,allwords
0,There are constants alpha and beta suc...,5,There constants alpha beta frac x alpha x beta...,15,2,19
1,The length of the segment between the points ...,5,The length segment points sqrt units What prod...,10,2,28
2,Chewbacca has 20 pieces of cherry gum and 30 p...,5,Chewbacca pieces cherry gum pieces grape gum S...,44,5,81
3,"For some constants a and b, let [f(x) = ...",5,For constants b let f x left begin array cl ax...,31,3,50
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,2,Calculate sum cdots,3,1,15

**FUNCTION TO COUNT THE MATH SYMBOLS IN EACH WORD PROBLEM**

In [170]:
math_symbols = []
l = "!@#$%^&*()[]{}:;<>+=-/?.,"
for i in l:
  math_symbols.append(i)

In [171]:

def count_symbols(data):
  total_count = 0
  data = data.split()
  for word in data: 
    if word in math_symbols:
      total_count = total_count+1
  return total_count

In [172]:
df_liststring['symbols'] = df_liststring['Problem '].apply(count_symbols)

In [173]:
df_liststring.head()

,Problem,Level,liststring,mathword_count,countsent,allwords,symbols
0,There are constants alpha and beta suc...,5,There constants alpha beta frac x alpha x beta...,15,2,19,3
1,The length of the segment between the points ...,5,The length segment points sqrt units What prod...,10,2,28,1
2,Chewbacca has 20 pieces of cherry gum and 30 p...,5,Chewbacca pieces cherry gum pieces grape gum S...,44,5,81,1
3,"For some constants a and b, let [f(x) = ...",5,For constants b let f x left begin array cl ax...,31,3,50,11
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,2,Calculate sum cdots,3,1,15,6

**FUNCTION TO COUNT THE NUMBERS IN EACH MATH WORD PROBLEM**

In [174]:
def count_nums(data):
  total_count = 0
  data = data.split()
  for word in data: 
    if word.isalpha() == False:
      total_count = total_count+1
  return total_count

In [175]:
df_liststring['numbers'] = df_liststring['Problem '].apply(count_nums)

In [176]:
df_liststring.head()

,Problem,Level,liststring,mathword_count,countsent,allwords,symbols,numbers
0,There are constants alpha and beta suc...,5,There constants alpha beta frac x alpha x beta...,15,2,19,3,8
1,The length of the segment between the points ...,5,The length segment points sqrt units What prod...,10,2,28,1,8
2,Chewbacca has 20 pieces of cherry gum and 30 p...,5,Chewbacca pieces cherry gum pieces grape gum S...,44,5,81,1,10
3,"For some constants a and b, let [f(x) = ...",5,For constants b let f x left begin array cl ax...,31,3,50,11,26
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,2,Calculate sum cdots,3,1,15,6,11

**COUNT OF MATH VOCAB WORD IN EACH SENTENCE ('mathword_count'/'countsent')**
* TOTAL MATH VOCAB IN PROBLEM/NUMBER OF SENTENCES IN PROBLEM

In [178]:
df_liststring['mathword'] = df_liststring['mathword_count']/df_liststring['countsent']
df_liststring.head()

,Problem,Level,liststring,mathword_count,countsent,allwords,symbols,numbers,mathword
0,There are constants alpha and beta suc...,5,There constants alpha beta frac x alpha x beta...,15,2,19,3,8,7.500000
1,The length of the segment between the points ...,5,The length segment points sqrt units What prod...,10,2,28,1,8,5.000000
2,Chewbacca has 20 pieces of cherry gum and 30 p...,5,Chewbacca pieces cherry gum pieces grape gum S...,44,5,81,1,10,8.800000
3,"For some constants a and b, let [f(x) = ...",5,For constants b let f x left begin array cl ax...,31,3,50,11,26,10.333333
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,2,Calculate sum cdots,3,1,15,6,11,3.000000

FUNCTION FOR CALCULATING NUMBER OF ALPHABETS (CHARACTERS) IN WORD PROBLEM

In [179]:
def count_words(df_col):
  count = 0
  for i in df_col:
    for j in i:
      count = count+1
  return count

In [180]:
df_liststring['word_sum'] = df_liststring['liststring'].apply(count_words)

**word_sum = CMVW**

In [181]:
df_liststring.head()

,Problem,Level,liststring,mathword_count,countsent,allwords,symbols,numbers,mathword,word_sum
0,There are constants alpha and beta suc...,5,There constants alpha beta frac x alpha x beta...,15,2,19,3,8,7.500000,71
1,The length of the segment between the points ...,5,The length segment points sqrt units What prod...,10,2,28,1,8,5.000000,65
2,Chewbacca has 20 pieces of cherry gum and 30 p...,5,Chewbacca pieces cherry gum pieces grape gum S...,44,5,81,1,10,8.800000,263
3,"For some constants a and b, let [f(x) = ...",5,For constants b let f x left begin array cl ax...,31,3,50,11,26,10.333333,122
4,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,2,Calculate sum cdots,3,1,15,6,11,3.000000,19

In [182]:
WordsPerSentence = []
#MathWordsPerSentence = []
MathSymbolsPerSentence = [] 
NumCountPerSentence = []

**CALCULATION OF:**
1. WordsPerSentence
2. MathSymbolsPerSentence
3. NumCountPerSentence

In [183]:
for i in df_liststring.iloc[:,0]:
  s = count_sentences(i)
  w = count_allwords(i)
  ms = count_symbols(i)
  n = count_nums(i) 
  mw = word_length(i)

  WordsPerSentence.append(w/s)  
  MathSymbolsPerSentence.append(ms/s)   
  NumCountPerSentence.append(n/s)  
  #MathWordsPerSentence.append(mw/s)

In [184]:
df_data = pd.DataFrame() 
df_data["WordsPerSentence"] = WordsPerSentence
df_data["MathSymbolsPerSentence"] = MathSymbolsPerSentence
df_data["NumCountPerSentence"] = NumCountPerSentence
#df_data["MathWordsPerSentence"] = MathWordsPerSentence
df_data["Level"] = df.iloc[:,1]
df_data["mathword"] = df_liststring.iloc[:,8]
df_data["Problem"] = df_liststring.iloc[:,0]
df_data["mathword_count"] = df_liststring.iloc[:,3]
df_data["countsent"] = df_liststring.iloc[:,4]
df_data["allwords"] = df_liststring.iloc[:,5]
df_data["symbols"] = df_liststring.iloc[:,6]
df_data["numbers"] = df_liststring.iloc[:,7]
df_data["word_sum"] = df_liststring.iloc[:,9]
df_data.head(10)

,WordsPerSentence,MathSymbolsPerSentence,NumCountPerSentence,Level,mathword,Problem,mathword_count,countsent,allwords,symbols,numbers,word_sum
0,9.500000,1.500000,4.000000,5,7.500000,There are constants alpha and beta suc...,15,2,19,3,8,71
1,14.000000,0.500000,4.000000,5,5.000000,The length of the segment between the points ...,10,2,28,1,8,65
2,16.200000,0.200000,2.000000,5,8.800000,Chewbacca has 20 pieces of cherry gum and 30 p...,44,5,81,1,10,263
3,16.666667,3.666667,8.666667,5,10.333333,"For some constants a and b, let [f(x) = ...",31,3,50,11,26,122
4,15.000000,6.000000,11.000000,2,3.000000,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,3,1,15,6,11,19
5,17.333333,1.000000,6.666667,4,15.666667,What is the number of units in the area of the...,47,3,52,3,20,238
6,18.000000,1.000000,2.000000,4,10.000000,Find the positive value of n such that the e...,10,1,18,1,2,56
7,26.000000,7.000000,16.000000,3,9.000000,Find the leading coefficient in the polynomial...,9,1,26,7,16,54
8,10.000000,1.000000,4.000000,5,5.000000,Find the greatest a such that frac{7 sqr...,5,1,10,1,4,28
9,14.666667,0.000000,2.333333,4,9.333333,The Bank of Springfield's Super High Yield sav...,28,3,44,0,7,183

**FUNCTION TO COUNT SYLLABLES IN EACH WORD PROBLEM**

**Counted number of syllables.**

In [185]:
def syllable_count(df_col):
    df_col = df_col.lower()
    count = 0
    vowels = "aeiou"
    if df_col[0] in vowels:
        count += 1
    for index in range(1, len(df_col)):
        if df_col[index] in vowels and df_col[index - 1] not in vowels:
            count += 1
    if df_col.endswith("e"):
        count -= 1
    if count == 0:
        count += 1
    return count

In [186]:
df_data['syllables'] = df_data['Problem'].apply(syllable_count)

In [187]:
df_data.head()

,WordsPerSentence,MathSymbolsPerSentence,NumCountPerSentence,Level,mathword,Problem,mathword_count,countsent,allwords,symbols,numbers,word_sum,syllables
0,9.500000,1.500000,4.000000,5,7.500000,There are constants alpha and beta suc...,15,2,19,3,8,71,25
1,14.000000,0.500000,4.000000,5,5.000000,The length of the segment between the points ...,10,2,28,1,8,65,30
2,16.200000,0.200000,2.000000,5,8.800000,Chewbacca has 20 pieces of cherry gum and 30 p...,44,5,81,1,10,263,107
3,16.666667,3.666667,8.666667,5,10.333333,"For some constants a and b, let [f(x) = ...",31,3,50,11,26,122,36
4,15.000000,6.000000,11.000000,2,3.000000,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,3,1,15,6,11,19,7

**FUNCTION TO COUNT OF POLY SYLLABLES IN EACH WORD PROBLEM**

In [188]:
def count_poly_syllables(df_col):
  total_count = 0
  df_col = df_col.split()
  for word in df_col: 
    #print(word)
    temp = syllable_count(word)
    if temp>=3:
      total_count = total_count+temp
  return total_count

In [189]:
df_data['poly_syllables'] = df_data['Problem'].apply(count_poly_syllables)

In [190]:
df_data.head()

,WordsPerSentence,MathSymbolsPerSentence,NumCountPerSentence,Level,mathword,Problem,mathword_count,countsent,allwords,symbols,numbers,word_sum,syllables,poly_syllables
0,9.500000,1.500000,4.000000,5,7.500000,There are constants alpha and beta suc...,15,2,19,3,8,71,25,0
1,14.000000,0.500000,4.000000,5,5.000000,The length of the segment between the points ...,10,2,28,1,8,65,30,0
2,16.200000,0.200000,2.000000,5,8.800000,Chewbacca has 20 pieces of cherry gum and 30 p...,44,5,81,1,10,263,107,6
3,16.666667,3.666667,8.666667,5,10.333333,"For some constants a and b, let [f(x) = ...",31,3,50,11,26,122,36,7
4,15.000000,6.000000,11.000000,2,3.000000,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,3,1,15,6,11,19,7,3

1. word_length = mathword in word Problem
2. count_sentences = number of sentences in word Problem
3. count_allwords = all words in word Problem
4. count_symbols = math symbols in word Problem
5. count_nums = count numbers in word Problem
6. syllable_count = number of syllables in word problem
7. count_poly_syllables = number of poly syllables in word problem
8. count_words = total alphabets sum in word Problem

**CALCULATION OF DIFFERENT INDICES**
1. Gunning Fog Index
2. Flesch - Kincaid Readability Index
3. SMOG (Simple Measure of Gobbledygook) Index
4. Automated Readability Index
5. Coleman-Liau Index

**Gunning Fog Index**
0.4[ (words/sentence) + 100(TMVC/words) ]

In [191]:
# 0.4[ (words/sentence) + 100(TMVC/total words) ] 
#(words/sentence) = ASL
#(TMVC/total words) = PMW

GF = []
for i in df.iloc[:,0]:
  w = count_allwords(i)
  c = word_length(i)
  s = count_sentences(i)
  gf_score = (w/s) + (100*c/w)
  GF.append(0.4*gf_score)

In [192]:
len(GF)

1744

**Flesch - Kincaid Readability Index**

In [193]:
#Formula: 206.835 - 1.015(total words/total sentences) - 84.6(TMVC/total words)
#(total words/total sentences) = ASL
FK = []
for i in df.iloc[:,0]:
  w = count_allwords(i)
  c = word_length(i)
  s = count_sentences(i)
  fk_score = (1.015*w/s) + (84.6*c/w)
  fk_score = 206.835 - fk_score 
  FK.append(fk_score)

In [194]:
len(FK)

1744

**SMOG (Simple Measure of Gobbledygook) Index**

In [195]:
# Fromula: 3.1291 + 1.0430(sqrt( TMVC*30 /number of sentences/number of sentences))
SMOG = []
for i in df.iloc[:,0]:
  c = word_length(i)
  s = count_sentences(i)
  smog_score = np.sqrt(30*c/s/s)
  smog_score = smog_score * 1.0430
  SMOG.append(3.1291+smog_score)

In [196]:
len(SMOG)

1744

**Automated Readability Index**

4.71 x (CMVW/TMVC) + 0.5 x (TMVC/ no of sentences) – 21.43.

In [197]:
AR = []
for i in df.iloc[:,0]:
  c = word_length(i)
  w = count_words(i)
  s = count_sentences(i)
  ar_score = (4.71*w/c) + (0.5*c/s) - 21.43
  AR.append(ar_score)

In [198]:
len(AR)

1744

**Coleman-Liau Index**

In [199]:
#Formula: 0.0588(average number of math vocab words per 25 words) - 15.8 - 0.296(average number of sentences per 25 words)
#Formula: 0.0588(AMV) - 15.8 - 0.296(AMVS)
CL = []
for i in df.iloc[:,0]:
  w = count_allwords(i)
  c = word_length(i)
  s = count_sentences(i)
  term1 = 0.0588*c*25/w 
  term3 = 0.296*s*25/w 
  cl_score = term1-15.8-term3
  CL.append(cl_score)

In [200]:
len(CL)

1744

In [201]:
df_data["GF"]=GF
df_data["FK"]=FK
df_data["SMOG"]=SMOG
df_data["AR"]=AR
df_data["CL"]=CL
df_data.head(5)

,WordsPerSentence,MathSymbolsPerSentence,NumCountPerSentence,Level,mathword,Problem,mathword_count,countsent,allwords,symbols,numbers,word_sum,syllables,poly_syllables,GF,FK,SMOG,AR,CL
0,9.500000,1.500000,4.000000,5,7.500000,There are constants alpha and beta suc...,15,2,19,3,8,71,25,0,43.800000,112.592500,15.579742,19.512632,-15.108947
1,14.000000,0.500000,4.000000,5,5.000000,The length of the segment between the points ...,10,2,28,1,8,65,30,0,45.600000,108.025000,18.243606,10.129286,-14.858571
2,16.200000,0.200000,2.000000,5,8.800000,Chewbacca has 20 pieces of cherry gum and 30 p...,44,5,81,1,10,263,107,6,46.480000,105.792000,13.412043,10.161852,-14.786790
3,16.666667,3.666667,8.666667,5,10.333333,"For some constants a and b, let [f(x) = ...",31,3,50,11,26,122,36,7,46.666667,105.318333,16.594172,9.982333,-14.774000
4,15.000000,6.000000,11.000000,2,3.000000,Calculate the sum 1 + 3 + 5 + cdots + 15 + ...,3,1,15,6,11,19,7,3,46.000000,107.010000,25.254471,1.770000,-14.823333

In [202]:
y=df_data['Level']

In [203]:
# Remove one column Problem as index base
df_data.drop(df_data.columns[[5]], axis=1, inplace=True)

In [204]:
df_data.head()

,WordsPerSentence,MathSymbolsPerSentence,NumCountPerSentence,Level,mathword,mathword_count,countsent,allwords,symbols,numbers,word_sum,syllables,poly_syllables,GF,FK,SMOG,AR,CL
0,9.500000,1.500000,4.000000,5,7.500000,15,2,19,3,8,71,25,0,43.800000,112.592500,15.579742,19.512632,-15.108947
1,14.000000,0.500000,4.000000,5,5.000000,10,2,28,1,8,65,30,0,45.600000,108.025000,18.243606,10.129286,-14.858571
2,16.200000,0.200000,2.000000,5,8.800000,44,5,81,1,10,263,107,6,46.480000,105.792000,13.412043,10.161852,-14.786790
3,16.666667,3.666667,8.666667,5,10.333333,31,3,50,11,26,122,36,7,46.666667,105.318333,16.594172,9.982333,-14.774000
4,15.000000,6.000000,11.000000,2,3.000000,3,1,15,6,11,19,7,3,46.000000,107.010000,25.254471,1.770000,-14.823333

In [205]:
# Remove one column Problem as index base
df_data.drop(df_data.columns[[3]], axis=1, inplace=True)

In [206]:
df_data.head()

,WordsPerSentence,MathSymbolsPerSentence,NumCountPerSentence,mathword,mathword_count,countsent,allwords,symbols,numbers,word_sum,syllables,poly_syllables,GF,FK,SMOG,AR,CL
0,9.500000,1.500000,4.000000,7.500000,15,2,19,3,8,71,25,0,43.800000,112.592500,15.579742,19.512632,-15.108947
1,14.000000,0.500000,4.000000,5.000000,10,2,28,1,8,65,30,0,45.600000,108.025000,18.243606,10.129286,-14.858571
2,16.200000,0.200000,2.000000,8.800000,44,5,81,1,10,263,107,6,46.480000,105.792000,13.412043,10.161852,-14.786790
3,16.666667,3.666667,8.666667,10.333333,31,3,50,11,26,122,36,7,46.666667,105.318333,16.594172,9.982333,-14.774000
4,15.000000,6.000000,11.000000,3.000000,3,1,15,6,11,19,7,3,46.000000,107.010000,25.254471,1.770000,-14.823333

In [213]:
num_attr_1 = ['WordsPerSentence', 'MathSymbolsPerSentence', 'NumCountPerSentence', 'mathword', 'mathword_count', 'countsent', 'allwords', 'symbols', 'numbers', 'word_sum', 'syllables', 'poly_syllables', 'GF', 'FK', 'SMOG', 'AR', 'CL']
#model building with all variables

In [214]:
#num_attr = ['GF', 'FK', 'SMOG', 'AR', 'CL']
#model building with only 5 indices

In [215]:
# Train-Test-Split is performed

from sklearn.model_selection import train_test_split

# Splitting the data into train and test
X_train, X_test, y_train, y_test = train_test_split(df_data, y, train_size=0.7, random_state=42)
X_train.shape, X_test.shape

((1220, 17), (524, 17))

In [216]:
scaler = StandardScaler()
scaler.fit(X_train[num_attr_1])

StandardScaler()

In [217]:
X_train_std = scaler.transform(X_train[num_attr_1])
X_test_std = scaler.transform(X_test[num_attr_1])

In [218]:
print(X_train_std.shape)
print(X_test_std.shape)

(1220, 17)
(524, 17)

In [219]:
print(y_train.value_counts(normalize=True)*100)
print("\n")
print(y_test.value_counts(normalize=True)*100)

5    25.081967
4    23.114754
3    22.213115
2    19.672131
1     9.918033
Name: Level, dtype: float64


5    24.809160
3    23.091603
4    22.137405
2    19.083969
1    10.877863
Name: Level, dtype: float64

Model Building

In [220]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score, classification_report

In [221]:
def perceptron_classifier (X_train_std, y_train, X_test_std, y_test):
  p = Perceptron(random_state=150)
  p.fit(X_train_std, y_train)
  predictions_train = p.predict(X_train_std)
  predictions_test = p.predict(X_test_std)
  train_score = accuracy_score(predictions_train, y_train)
  #print("score on train data: ", train_score)
  test_score = f1_score(predictions_test, y_test, average='weighted' )
  print("Perceptron F1 score:", test_score)

In [222]:
from sklearn.linear_model import Perceptron
perceptron_classifier(X_train_std, y_train, X_test_std, y_test)

Perceptron F1 score: 0.32820766525289286

**Decision Tree**

In [223]:
clf_dt = DecisionTreeClassifier(max_depth=5)

In [224]:
clf_dt.fit(X_train_std,y_train)

DecisionTreeClassifier(max_depth=5)

In [225]:
y_pred_train = clf_dt.predict(X_train_std)
y_pred_test = clf_dt.predict(X_test_std)

In [226]:
def classifcation_report_train_test(y_train, y_train_pred, y_test, y_test_pred):

    print('''
            =========================================
               CLASSIFICATION REPORT FOR TRAIN DATA
            =========================================
            ''')
    print(classification_report(y_train, y_train_pred, digits=4))

    print('''
            =========================================
               CLASSIFICATION REPORT FOR TEST DATA
            =========================================
            ''')
    print(classification_report(y_test, y_test_pred, digits=4))

In [227]:
scores = pd.DataFrame(columns=['Model', 'Train_Accuracy', 'Train_Recall', 'Train_Precision', 'Train_F1_Score', 
                               'Test_Accuracy', 'Test_Recall', 'Test_Precision', 'Test_F1_Score'])

def get_metrics(train_actual, train_predicted, test_actual, test_predicted, model_description, dataframe):

    train_accuracy  = accuracy_score(train_actual, train_predicted)
    train_recall    = recall_score(train_actual, train_predicted, average="weighted")
    train_precision = precision_score(train_actual, train_predicted, average="weighted")
    train_f1score   = f1_score(train_actual, train_predicted, average="weighted")
    
    test_accuracy   = accuracy_score(test_actual, test_predicted)
    test_recall     = recall_score(test_actual, test_predicted, average="weighted")
    test_precision  = precision_score(test_actual, test_predicted, average="weighted")
    test_f1score    = f1_score(test_actual, test_predicted, average="weighted")

    dataframe       = dataframe.append(pd.Series([model_description, 
                                                  train_accuracy, train_recall, train_precision, train_f1score,
                                                  test_accuracy, test_recall, test_precision, test_f1score],
                                                 index=scores.columns ), 
                                       ignore_index=True)

    return(dataframe)

In [228]:
scores = get_metrics(y_train, y_pred_train, y_test, y_pred_test, "DecisionTrees", scores)
scores

,Model,Train_Accuracy,Train_Recall,Train_Precision,Train_F1_Score,Test_Accuracy,Test_Recall,Test_Precision,Test_F1_Score
0,DecisionTrees,0.429508,0.429508,0.495197,0.415046,0.322519,0.322519,0.329887,0.300519

**Random Forest**

In [229]:
clf_rf = RandomForestClassifier()

In [230]:
clf_rf.fit(X=X_train_std, y=y_train)

RandomForestClassifier()

In [231]:
y_pred_train1 = clf_rf.predict(X_train_std)
y_pred_test1 = clf_rf.predict(X_test_std)

In [232]:
classifcation_report_train_test(y_train, y_pred_train1, y_test, y_pred_test1)

            =========================================
               CLASSIFICATION REPORT FOR TRAIN DATA
            =========================================

              precision    recall  f1-score   support

           1     1.0000    0.9835    0.9917       121
           2     0.9876    0.9958    0.9917       240
           3     0.9963    0.9852    0.9907       271
           4     0.9826    1.0000    0.9912       282
           5     1.0000    0.9935    0.9967       306

    accuracy                         0.9926      1220
   macro avg     0.9933    0.9916    0.9924      1220
weighted avg     0.9927    0.9926    0.9926      1220


            =========================================
               CLASSIFICATION REPORT FOR TEST DATA
            =========================================

              precision    recall  f1-score   support

           1     0.3333    0.1754    0.2299        57
           2     0.2823    0.3500    0.3125       100
           3     0.3103    0.2975    0.3038       121
           4     0.3204    0.2845    0.3014       116
           5     0.4702    0.5462    0.5053       130

    accuracy                         0.3531       524
   macro avg     0.3433    0.3307    0.3306       524
weighted avg     0.3494    0.3531    0.3469       524

In [233]:
scores = get_metrics(y_train, y_pred_train1, y_test, y_pred_test1, "RandomForest", scores)
scores

,Model,Train_Accuracy,Train_Recall,Train_Precision,Train_F1_Score,Test_Accuracy,Test_Recall,Test_Precision,Test_F1_Score
0,DecisionTrees,0.429508,0.429508,0.495197,0.415046,0.322519,0.322519,0.329887,0.300519
1,RandomForest,0.992623,0.992623,0.992705,0.992627,0.353053,0.353053,0.349367,0.346881

**AdaBoost**

In [234]:
clf_adaboost =  AdaBoostClassifier()

In [235]:
clf_adaboost.fit(X_train_std, y_train)

AdaBoostClassifier()

In [236]:
y_pred_train2 = clf_adaboost.predict(X_train_std)
y_pred_test2 = clf_adaboost.predict(X_test_std)

In [237]:
classifcation_report_train_test(y_train, y_pred_train2, y_test, y_pred_test2)

            =========================================
               CLASSIFICATION REPORT FOR TRAIN DATA
            =========================================

              precision    recall  f1-score   support

           1     0.4023    0.2893    0.3365       121
           2     0.3593    0.3458    0.3524       240
           3     0.3442    0.2731    0.3045       271
           4     0.3211    0.2801    0.2992       282
           5     0.4376    0.6307    0.5167       306

    accuracy                         0.3803      1220
   macro avg     0.3729    0.3638    0.3619      1220
weighted avg     0.3710    0.3803    0.3691      1220


            =========================================
               CLASSIFICATION REPORT FOR TEST DATA
            =========================================

              precision    recall  f1-score   support

           1     0.2222    0.1754    0.1961        57
           2     0.2288    0.2700    0.2477       100
           3     0.3371    0.2479    0.2857       121
           4     0.2581    0.2069    0.2297       116
           5     0.4078    0.5615    0.4725       130

    accuracy                         0.3130       524
   macro avg     0.2908    0.2924    0.2863       524
weighted avg     0.3040    0.3130    0.3026       524

In [238]:
scores = get_metrics(y_train, y_pred_train2, y_test, y_pred_test2, "Adaboost", scores)
scores

,Model,Train_Accuracy,Train_Recall,Train_Precision,Train_F1_Score,Test_Accuracy,Test_Recall,Test_Precision,Test_F1_Score
0,DecisionTrees,0.429508,0.429508,0.495197,0.415046,0.322519,0.322519,0.329887,0.300519
1,RandomForest,0.992623,0.992623,0.992705,0.992627,0.353053,0.353053,0.349367,0.346881
2,Adaboost,0.380328,0.380328,0.371037,0.369132,0.312977,0.312977,0.303982,0.302641

**Gradient Boosting Classifier**

In [239]:
clf_gbm = GradientBoostingClassifier()

In [240]:
clf_gbm.fit(X=X_train_std, y=y_train)

GradientBoostingClassifier()

In [241]:
y_pred_train3 = clf_gbm.predict(X_train_std)
y_pred_test3 = clf_gbm.predict(X_test_std)

In [242]:
classifcation_report_train_test(y_train, y_pred_train3, y_test, y_pred_test3)

            =========================================
               CLASSIFICATION REPORT FOR TRAIN DATA
            =========================================

              precision    recall  f1-score   support

           1     0.9140    0.7025    0.7944       121
           2     0.7817    0.7458    0.7633       240
           3     0.7158    0.7528    0.7338       271
           4     0.7651    0.7624    0.7638       282
           5     0.7651    0.8301    0.7962       306

    accuracy                         0.7680      1220
   macro avg     0.7883    0.7587    0.7703      1220
weighted avg     0.7722    0.7680    0.7682      1220


            =========================================
               CLASSIFICATION REPORT FOR TEST DATA
            =========================================

              precision    recall  f1-score   support

           1     0.2703    0.1754    0.2128        57
           2     0.2389    0.2700    0.2535       100
           3     0.2783    0.2645    0.2712       121
           4     0.2991    0.2759    0.2870       116
           5     0.4671    0.5462    0.5035       130

    accuracy                         0.3282       524
   macro avg     0.3107    0.3064    0.3056       524
weighted avg     0.3213    0.3282    0.3226       524

In [243]:
scores = get_metrics(y_train, y_pred_train3, y_test, y_pred_test3, "GBM", scores)
scores

,Model,Train_Accuracy,Train_Recall,Train_Precision,Train_F1_Score,Test_Accuracy,Test_Recall,Test_Precision,Test_F1_Score
0,DecisionTrees,0.429508,0.429508,0.495197,0.415046,0.322519,0.322519,0.329887,0.300519
1,RandomForest,0.992623,0.992623,0.992705,0.992627,0.353053,0.353053,0.349367,0.346881
2,Adaboost,0.380328,0.380328,0.371037,0.369132,0.312977,0.312977,0.303982,0.302641
3,GBM,0.768033,0.768033,0.772166,0.768208,0.328244,0.328244,0.321344,0.322606

**SVM Model**

In [244]:
linear_svm = SVC(kernel='linear', C=1)

In [245]:
linear_svm.fit(X=X_train_std, y= y_train)

SVC(C=1, kernel='linear')

In [246]:
y_pred_train4 = linear_svm.predict(X_train_std)
y_pred_test4 = linear_svm.predict(X_test_std)

In [247]:
classifcation_report_train_test(y_train, y_pred_train4, y_test, y_pred_test4)

            =========================================
               CLASSIFICATION REPORT FOR TRAIN DATA
            =========================================

              precision    recall  f1-score   support

           1     0.0000    0.0000    0.0000       121
           2     0.3210    0.3250    0.3230       240
           3     0.2841    0.1845    0.2237       271
           4     0.3094    0.2908    0.2998       282
           5     0.3843    0.6732    0.4893       306

    accuracy                         0.3410      1220
   macro avg     0.2598    0.2947    0.2672      1220
weighted avg     0.2942    0.3410    0.3053      1220


            =========================================
               CLASSIFICATION REPORT FOR TEST DATA
            =========================================

              precision    recall  f1-score   support

           1     0.0000    0.0000    0.0000        57
           2     0.2907    0.2500    0.2688       100
           3     0.2469    0.1653    0.1980       121
           4     0.2403    0.2672    0.2531       116
           5     0.3553    0.6231    0.4525       130

    accuracy                         0.2996       524
   macro avg     0.2266    0.2611    0.2345       524
weighted avg     0.2538    0.2996    0.2653       524

In [248]:
scores = get_metrics(y_train, y_pred_train4, y_test, y_pred_test4, "SVM", scores)
scores

,Model,Train_Accuracy,Train_Recall,Train_Precision,Train_F1_Score,Test_Accuracy,Test_Recall,Test_Precision,Test_F1_Score
0,DecisionTrees,0.429508,0.429508,0.495197,0.415046,0.322519,0.322519,0.329887,0.300519
1,RandomForest,0.992623,0.992623,0.992705,0.992627,0.353053,0.353053,0.349367,0.346881
2,Adaboost,0.380328,0.380328,0.371037,0.369132,0.312977,0.312977,0.303982,0.302641
3,GBM,0.768033,0.768033,0.772166,0.768208,0.328244,0.328244,0.321344,0.322606
4,SVM,0.340984,0.340984,0.294173,0.305262,0.299618,0.299618,0.253829,0.265313

**KNN**

In [249]:
knn = KNeighborsClassifier(n_neighbors=7)

In [250]:
knn.fit(X=X_train_std, y=y_train)

KNeighborsClassifier(n_neighbors=7)

In [251]:
y_pred_train5 = knn.predict(X_train_std)
y_pred_test5 = knn.predict(X_test_std)

In [252]:
classifcation_report_train_test(y_train, y_pred_train5, y_test, y_pred_test5)

            =========================================
               CLASSIFICATION REPORT FOR TRAIN DATA
            =========================================

              precision    recall  f1-score   support

           1     0.4027    0.4959    0.4444       121
           2     0.4375    0.4958    0.4648       240
           3     0.4793    0.4280    0.4522       271
           4     0.4936    0.4078    0.4466       282
           5     0.5586    0.5915    0.5746       306

    accuracy                         0.4844      1220
   macro avg     0.4743    0.4838    0.4765      1220
weighted avg     0.4867    0.4844    0.4833      1220


            =========================================
               CLASSIFICATION REPORT FOR TEST DATA
            =========================================

              precision    recall  f1-score   support

           1     0.2571    0.3158    0.2835        57
           2     0.2377    0.2900    0.2613       100
           3     0.3333    0.2975    0.3144       121
           4     0.2857    0.2414    0.2617       116
           5     0.3968    0.3846    0.3906       130

    accuracy                         0.3073       524
   macro avg     0.3021    0.3059    0.3023       524
weighted avg     0.3120    0.3073    0.3081       524

In [253]:
scores = get_metrics(y_train, y_pred_train5, y_test, y_pred_test5, "KNN", scores)
scores

,Model,Train_Accuracy,Train_Recall,Train_Precision,Train_F1_Score,Test_Accuracy,Test_Recall,Test_Precision,Test_F1_Score
0,DecisionTrees,0.429508,0.429508,0.495197,0.415046,0.322519,0.322519,0.329887,0.300519
1,RandomForest,0.992623,0.992623,0.992705,0.992627,0.353053,0.353053,0.349367,0.346881
2,Adaboost,0.380328,0.380328,0.371037,0.369132,0.312977,0.312977,0.303982,0.302641
3,GBM,0.768033,0.768033,0.772166,0.768208,0.328244,0.328244,0.321344,0.322606
4,SVM,0.340984,0.340984,0.294173,0.305262,0.299618,0.299618,0.253829,0.265313
5,KNN,0.484426,0.484426,0.486684,0.483335,0.307252,0.307252,0.312006,0.308137

**GNB**

In [254]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()

In [255]:
nb.fit(X=X_train_std, y=y_train)

GaussianNB()

In [256]:
y_pred_train6 = nb.predict(X_train_std)
y_pred_test6 = nb.predict(X_test_std)

In [257]:
classifcation_report_train_test(y_train, y_pred_train6, y_test, y_pred_test6)

            =========================================
               CLASSIFICATION REPORT FOR TRAIN DATA
            =========================================

              precision    recall  f1-score   support

           1     0.2500    0.2727    0.2609       121
           2     0.2181    0.5333    0.3096       240
           3     0.1351    0.0185    0.0325       271
           4     0.2534    0.3298    0.2866       282
           5     0.4639    0.1471    0.2233       306

    accuracy                         0.2492      1220
   macro avg     0.2641    0.2603    0.2226      1220
weighted avg     0.2726    0.2492    0.2162      1220


            =========================================
               CLASSIFICATION REPORT FOR TEST DATA
            =========================================

              precision    recall  f1-score   support

           1     0.2500    0.1754    0.2062        57
           2     0.1705    0.4400    0.2458       100
           3     0.2308    0.0248    0.0448       121
           4     0.3046    0.4569    0.3655       116
           5     0.5897    0.1769    0.2722       130

    accuracy                         0.2538       524
   macro avg     0.3091    0.2548    0.2269       524
weighted avg     0.3268    0.2538    0.2281       524

In [258]:
scores = get_metrics(y_train, y_pred_train6, y_test, y_pred_test6, "GNB", scores) 
scores

,Model,Train_Accuracy,Train_Recall,Train_Precision,Train_F1_Score,Test_Accuracy,Test_Recall,Test_Precision,Test_F1_Score
0,DecisionTrees,0.429508,0.429508,0.495197,0.415046,0.322519,0.322519,0.329887,0.300519
1,RandomForest,0.992623,0.992623,0.992705,0.992627,0.353053,0.353053,0.349367,0.346881
2,Adaboost,0.380328,0.380328,0.371037,0.369132,0.312977,0.312977,0.303982,0.302641
3,GBM,0.768033,0.768033,0.772166,0.768208,0.328244,0.328244,0.321344,0.322606
4,SVM,0.340984,0.340984,0.294173,0.305262,0.299618,0.299618,0.253829,0.265313
5,KNN,0.484426,0.484426,0.486684,0.483335,0.307252,0.307252,0.312006,0.308137
6,GNB,0.249180,0.249180,0.272643,0.216241,0.253817,0.253817,0.326770,0.228122